### ISSUE TITLE
Spanish translation (question)

### ISSUE THREAD

**Issue by vacilagodzila** [liberodark/Crashlands#4]
Hello, I was seeing your repo and I'm very interested in starting with Spanish translation for the .json file. Should I create `spanish.json` file in the `assets` folder with the translations?

Sadly, I'm at work rn and can't open this link for [Spanish](http://steamcommunity.com/app/391730/discussions/0/133255603285038720/) since my network blocks anything that has to do with games and entertainment.

**Comment by liberodark** [comment]
Is just steam link is nothing is for speak or view spanish discussion
Have created spanish json for you !

**Comment by vacilagodzila** [comment]
Again, @liberodark , Should I create spanish.json file in the assets folder with the translations?
